export const GET_LIST_CATEGORIES = "GET_LIST_CATEGORIES";
export const GET_LIST_CATEGORIES_SUCCESS = "GET_LIST_CATEGORIES_SUCCESS";
export const GET_LIST_CATEGORIES_ERROR = "GET_LIST_CATEGORIES_ERROR";
