export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_ERROR = "GET_LIST_PRODUCT_ERROR";

export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_ERROR = "GET_DETAIL_PRODUCT_ERROR";